# -------------------------------------------------------------------
# Taps
# -------------------------------------------------------------------

tap "mongodb/brew"
tap "theseal/ssh-askpass"
tap "d12frosted/emacs-plus"


# -------------------------------------------------------------------
# Core command-line tools
# -------------------------------------------------------------------

brew "git"
brew "git-lfs"
brew "coreutils"
brew "wget"
brew "tree"
brew "tmux"
brew "htop"
brew "sevenzip"

brew "fd"
brew "fzf"
brew "bat"
brew "ripgrep"

brew "jq"
brew "yq"
brew "pandoc"
brew "enchant"

# -------------------------------------------------------------------
# Build tooling
# -------------------------------------------------------------------

brew "autoconf"
brew "automake"
brew "cmake"
brew "pkg-config"


# -------------------------------------------------------------------
# Shell and configuration validation
# -------------------------------------------------------------------

brew "shellcheck"
brew "yamllint"


# -------------------------------------------------------------------
# Org, PDF, image and diagram support
# -------------------------------------------------------------------

brew "poppler"
brew "texlive"
brew "imagemagick"
brew "plantuml"


# -------------------------------------------------------------------
# GitHub
# -------------------------------------------------------------------

brew "gh"


# -------------------------------------------------------------------
# Containers
# -------------------------------------------------------------------

cask "docker"

brew "lazydocker"
brew "hadolint"
brew "trivy"


# -------------------------------------------------------------------
# Kubernetes and cloud tooling
# -------------------------------------------------------------------

brew "minikube"
brew "kubernetes-cli"
brew "kubeseal"
brew "kubetail"
brew "kubespy"
brew "helm"
brew "argocd"
brew "opentofu"
brew "tofu-ls"

brew "awscli"


# -------------------------------------------------------------------
# Databases
# -------------------------------------------------------------------

brew "postgresql@16"
brew "pgformatter"
brew "mongodb/brew/mongodb-community"


# -------------------------------------------------------------------
# Kafka
# -------------------------------------------------------------------

brew "librdkafka"


# -------------------------------------------------------------------
# C and C++
# -------------------------------------------------------------------

brew "ccls"
brew "llvm"

# -------------------------------------------------------------------
# go
# -------------------------------------------------------------------
brew "goenv"

# -------------------------------------------------------------------
# Python / Pyenv Deps
# -------------------------------------------------------------------
brew "openssl@3"
brew "readline"
brew "sqlite"
brew "xz"
brew "tcl-tk"
brew "zstd"
brew "python-tk"

# -------------------------------------------------------------------
# Networking
# -------------------------------------------------------------------

brew "bind"
brew "mtr"
brew "nmap"

# Specialized DNS enumeration. Remove if unused.
brew "dnsmap"


# -------------------------------------------------------------------
# Security and authentication
# -------------------------------------------------------------------

# Keep only if you use smart cards, PIV or PKCS#11.
brew "opensc"


# -------------------------------------------------------------------
# Desktop applications
# -------------------------------------------------------------------

cask "qutebrowser"
cask "google-chrome"
